/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LanesRouteImport } from './routes/lanes'
import { Route as PendingActivationRouteImport } from './routes/pending-activation'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StaffSignupRouteImport } from './routes/staff-signup'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDeliveriesRouteImport } from './routes/_authenticated/deliveries'
import { Route as AuthenticatedEtaBoardRouteImport } from './routes/_authenticated/eta-board'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedPackagesRouteImport } from './routes/_authenticated/packages'
import { Route as AuthenticatedRatesRouteImport } from './routes/_authenticated/rates'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedShipmentsRouteImport } from './routes/_authenticated/shipments'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as LanesOriginRouteImport } from './routes/lanes.$origin'
import { Route as TrackCodeRouteImport } from './routes/track.$code'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedCrmContactsRouteImport } from './routes/_authenticated/crm.contacts'
import { Route as AuthenticatedSourcingPosRouteImport } from './routes/_authenticated/sourcing.pos'
import { Route as AuthenticatedTreasuryAccountsRouteImport } from './routes/_authenticated/treasury.accounts'
import { Route as ApiPublicHooksPollShipmentEtaRouteImport } from './routes/api/public/hooks/poll-shipment-eta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LanesRoute = LanesRouteImport.update({
  id: '/lanes',
  path: '/lanes',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingActivationRoute = PendingActivationRouteImport.update({
  id: '/pending-activation',
  path: '/pending-activation',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSignupRoute = StaffSignupRouteImport.update({
  id: '/staff-signup',
  path: '/staff-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEtaBoardRoute = AuthenticatedEtaBoardRouteImport.update({
  id: '/eta-board',
  path: '/eta-board',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPackagesRoute = AuthenticatedPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRatesRoute = AuthenticatedRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShipmentsRoute = AuthenticatedShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LanesOriginRoute = LanesOriginRouteImport.update({
  id: '/$origin',
  path: '/$origin',
  getParentRoute: () => LanesRoute,
} as any)
const TrackCodeRoute = TrackCodeRouteImport.update({
  id: '/track/$code',
  path: '/track/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmContactsRoute =
  AuthenticatedCrmContactsRouteImport.update({
    id: '/crm/contacts',
    path: '/crm/contacts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSourcingPosRoute =
  AuthenticatedSourcingPosRouteImport.update({
    id: '/sourcing/pos',
    path: '/sourcing/pos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTreasuryAccountsRoute =
  AuthenticatedTreasuryAccountsRouteImport.update({
    id: '/treasury/accounts',
    path: '/treasury/accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksPollShipmentEtaRoute =
  ApiPublicHooksPollShipmentEtaRouteImport.update({
    id: '/api/public/hooks/poll-shipment-eta',
    path: '/api/public/hooks/poll-shipment-eta',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/lanes': typeof LanesRouteWithChildren
  '/pending-activation': typeof PendingActivationRoute
  '/portal': typeof PortalRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/staff-signup': typeof StaffSignupRoute
  '/tracking': typeof TrackingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/eta-board': typeof AuthenticatedEtaBoardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/rates': typeof AuthenticatedRatesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/shipments': typeof AuthenticatedShipmentsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/lanes/$origin': typeof LanesOriginRoute
  '/track/$code': typeof TrackCodeRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/crm/contacts': typeof AuthenticatedCrmContactsRoute
  '/sourcing/pos': typeof AuthenticatedSourcingPosRoute
  '/treasury/accounts': typeof AuthenticatedTreasuryAccountsRoute
  '/api/public/hooks/poll-shipment-eta': typeof ApiPublicHooksPollShipmentEtaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/lanes': typeof LanesRouteWithChildren
  '/pending-activation': typeof PendingActivationRoute
  '/portal': typeof PortalRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/staff-signup': typeof StaffSignupRoute
  '/tracking': typeof TrackingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/eta-board': typeof AuthenticatedEtaBoardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/rates': typeof AuthenticatedRatesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/shipments': typeof AuthenticatedShipmentsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/lanes/$origin': typeof LanesOriginRoute
  '/track/$code': typeof TrackCodeRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/crm/contacts': typeof AuthenticatedCrmContactsRoute
  '/sourcing/pos': typeof AuthenticatedSourcingPosRoute
  '/treasury/accounts': typeof AuthenticatedTreasuryAccountsRoute
  '/api/public/hooks/poll-shipment-eta': typeof ApiPublicHooksPollShipmentEtaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/lanes': typeof LanesRouteWithChildren
  '/pending-activation': typeof PendingActivationRoute
  '/portal': typeof PortalRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/staff-signup': typeof StaffSignupRoute
  '/tracking': typeof TrackingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRoute
  '/_authenticated/eta-board': typeof AuthenticatedEtaBoardRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/packages': typeof AuthenticatedPackagesRoute
  '/_authenticated/rates': typeof AuthenticatedRatesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/shipments': typeof AuthenticatedShipmentsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/lanes/$origin': typeof LanesOriginRoute
  '/track/$code': typeof TrackCodeRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/crm/contacts': typeof AuthenticatedCrmContactsRoute
  '/_authenticated/sourcing/pos': typeof AuthenticatedSourcingPosRoute
  '/_authenticated/treasury/accounts': typeof AuthenticatedTreasuryAccountsRoute
  '/api/public/hooks/poll-shipment-eta': typeof ApiPublicHooksPollShipmentEtaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accept-invite'
    | '/account'
    | '/auth'
    | '/change-password'
    | '/contact'
    | '/forgot-password'
    | '/lanes'
    | '/pending-activation'
    | '/portal'
    | '/quote'
    | '/services'
    | '/staff-signup'
    | '/tracking'
    | '/dashboard'
    | '/deliveries'
    | '/eta-board'
    | '/invoices'
    | '/packages'
    | '/rates'
    | '/reports'
    | '/shipments'
    | '/support'
    | '/lanes/$origin'
    | '/track/$code'
    | '/admin/audit'
    | '/admin/users'
    | '/crm/contacts'
    | '/sourcing/pos'
    | '/treasury/accounts'
    | '/api/public/hooks/poll-shipment-eta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accept-invite'
    | '/account'
    | '/auth'
    | '/change-password'
    | '/contact'
    | '/forgot-password'
    | '/lanes'
    | '/pending-activation'
    | '/portal'
    | '/quote'
    | '/services'
    | '/staff-signup'
    | '/tracking'
    | '/dashboard'
    | '/deliveries'
    | '/eta-board'
    | '/invoices'
    | '/packages'
    | '/rates'
    | '/reports'
    | '/shipments'
    | '/support'
    | '/lanes/$origin'
    | '/track/$code'
    | '/admin/audit'
    | '/admin/users'
    | '/crm/contacts'
    | '/sourcing/pos'
    | '/treasury/accounts'
    | '/api/public/hooks/poll-shipment-eta'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/accept-invite'
    | '/account'
    | '/auth'
    | '/change-password'
    | '/contact'
    | '/forgot-password'
    | '/lanes'
    | '/pending-activation'
    | '/portal'
    | '/quote'
    | '/services'
    | '/staff-signup'
    | '/tracking'
    | '/_authenticated/dashboard'
    | '/_authenticated/deliveries'
    | '/_authenticated/eta-board'
    | '/_authenticated/invoices'
    | '/_authenticated/packages'
    | '/_authenticated/rates'
    | '/_authenticated/reports'
    | '/_authenticated/shipments'
    | '/_authenticated/support'
    | '/lanes/$origin'
    | '/track/$code'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/users'
    | '/_authenticated/crm/contacts'
    | '/_authenticated/sourcing/pos'
    | '/_authenticated/treasury/accounts'
    | '/api/public/hooks/poll-shipment-eta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LanesRoute: typeof LanesRouteWithChildren
  PendingActivationRoute: typeof PendingActivationRoute
  PortalRoute: typeof PortalRoute
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRoute
  StaffSignupRoute: typeof StaffSignupRoute
  TrackingRoute: typeof TrackingRoute
  TrackCodeRoute: typeof TrackCodeRoute
  ApiPublicHooksPollShipmentEtaRoute: typeof ApiPublicHooksPollShipmentEtaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lanes': {
      id: '/lanes'
      path: '/lanes'
      fullPath: '/lanes'
      preLoaderRoute: typeof LanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-activation': {
      id: '/pending-activation'
      path: '/pending-activation'
      fullPath: '/pending-activation'
      preLoaderRoute: typeof PendingActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-signup': {
      id: '/staff-signup'
      path: '/staff-signup'
      fullPath: '/staff-signup'
      preLoaderRoute: typeof StaffSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eta-board': {
      id: '/_authenticated/eta-board'
      path: '/eta-board'
      fullPath: '/eta-board'
      preLoaderRoute: typeof AuthenticatedEtaBoardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/packages': {
      id: '/_authenticated/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthenticatedPackagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rates': {
      id: '/_authenticated/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof AuthenticatedRatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shipments': {
      id: '/_authenticated/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof AuthenticatedShipmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lanes/$origin': {
      id: '/lanes/$origin'
      path: '/$origin'
      fullPath: '/lanes/$origin'
      preLoaderRoute: typeof LanesOriginRouteImport
      parentRoute: typeof LanesRoute
    }
    '/track/$code': {
      id: '/track/$code'
      path: '/track/$code'
      fullPath: '/track/$code'
      preLoaderRoute: typeof TrackCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/contacts': {
      id: '/_authenticated/crm/contacts'
      path: '/crm/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof AuthenticatedCrmContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sourcing/pos': {
      id: '/_authenticated/sourcing/pos'
      path: '/sourcing/pos'
      fullPath: '/sourcing/pos'
      preLoaderRoute: typeof AuthenticatedSourcingPosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treasury/accounts': {
      id: '/_authenticated/treasury/accounts'
      path: '/treasury/accounts'
      fullPath: '/treasury/accounts'
      preLoaderRoute: typeof AuthenticatedTreasuryAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/poll-shipment-eta': {
      id: '/api/public/hooks/poll-shipment-eta'
      path: '/api/public/hooks/poll-shipment-eta'
      fullPath: '/api/public/hooks/poll-shipment-eta'
      preLoaderRoute: typeof ApiPublicHooksPollShipmentEtaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeliveriesRoute: typeof AuthenticatedDeliveriesRoute
  AuthenticatedEtaBoardRoute: typeof AuthenticatedEtaBoardRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedPackagesRoute: typeof AuthenticatedPackagesRoute
  AuthenticatedRatesRoute: typeof AuthenticatedRatesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedShipmentsRoute: typeof AuthenticatedShipmentsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedCrmContactsRoute: typeof AuthenticatedCrmContactsRoute
  AuthenticatedSourcingPosRoute: typeof AuthenticatedSourcingPosRoute
  AuthenticatedTreasuryAccountsRoute: typeof AuthenticatedTreasuryAccountsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedEtaBoardRoute: AuthenticatedEtaBoardRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedPackagesRoute: AuthenticatedPackagesRoute,
  AuthenticatedRatesRoute: AuthenticatedRatesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedShipmentsRoute: AuthenticatedShipmentsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedCrmContactsRoute: AuthenticatedCrmContactsRoute,
  AuthenticatedSourcingPosRoute: AuthenticatedSourcingPosRoute,
  AuthenticatedTreasuryAccountsRoute: AuthenticatedTreasuryAccountsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LanesRouteChildren {
  LanesOriginRoute: typeof LanesOriginRoute
}

const LanesRouteChildren: LanesRouteChildren = {
  LanesOriginRoute: LanesOriginRoute,
}

const LanesRouteWithChildren = LanesRoute._addFileChildren(LanesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LanesRoute: LanesRouteWithChildren,
  PendingActivationRoute: PendingActivationRoute,
  PortalRoute: PortalRoute,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRoute,
  StaffSignupRoute: StaffSignupRoute,
  TrackingRoute: TrackingRoute,
  TrackCodeRoute: TrackCodeRoute,
  ApiPublicHooksPollShipmentEtaRoute: ApiPublicHooksPollShipmentEtaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
