/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffSignupRouteImport } from './routes/staff-signup'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PendingActivationRouteImport } from './routes/pending-activation'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackCodeRouteImport } from './routes/track.$code'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedShipmentsRouteImport } from './routes/_authenticated/shipments'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRatesRouteImport } from './routes/_authenticated/rates'
import { Route as AuthenticatedPackagesRouteImport } from './routes/_authenticated/packages'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedDeliveriesRouteImport } from './routes/_authenticated/deliveries'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTreasuryAccountsRouteImport } from './routes/_authenticated/treasury.accounts'
import { Route as AuthenticatedSourcingPosRouteImport } from './routes/_authenticated/sourcing.pos'
import { Route as AuthenticatedCrmContactsRouteImport } from './routes/_authenticated/crm.contacts'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'

const StaffSignupRoute = StaffSignupRouteImport.update({
  id: '/staff-signup',
  path: '/staff-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingActivationRoute = PendingActivationRouteImport.update({
  id: '/pending-activation',
  path: '/pending-activation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackCodeRoute = TrackCodeRouteImport.update({
  id: '/track/$code',
  path: '/track/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShipmentsRoute = AuthenticatedShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRatesRoute = AuthenticatedRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPackagesRoute = AuthenticatedPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTreasuryAccountsRoute =
  AuthenticatedTreasuryAccountsRouteImport.update({
    id: '/treasury/accounts',
    path: '/treasury/accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSourcingPosRoute =
  AuthenticatedSourcingPosRouteImport.update({
    id: '/sourcing/pos',
    path: '/sourcing/pos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmContactsRoute =
  AuthenticatedCrmContactsRouteImport.update({
    id: '/crm/contacts',
    path: '/crm/contacts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pending-activation': typeof PendingActivationRoute
  '/portal': typeof PortalRoute
  '/staff-signup': typeof StaffSignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/rates': typeof AuthenticatedRatesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/shipments': typeof AuthenticatedShipmentsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/track/$code': typeof TrackCodeRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/crm/contacts': typeof AuthenticatedCrmContactsRoute
  '/sourcing/pos': typeof AuthenticatedSourcingPosRoute
  '/treasury/accounts': typeof AuthenticatedTreasuryAccountsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pending-activation': typeof PendingActivationRoute
  '/portal': typeof PortalRoute
  '/staff-signup': typeof StaffSignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/rates': typeof AuthenticatedRatesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/shipments': typeof AuthenticatedShipmentsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/track/$code': typeof TrackCodeRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/crm/contacts': typeof AuthenticatedCrmContactsRoute
  '/sourcing/pos': typeof AuthenticatedSourcingPosRoute
  '/treasury/accounts': typeof AuthenticatedTreasuryAccountsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/pending-activation': typeof PendingActivationRoute
  '/portal': typeof PortalRoute
  '/staff-signup': typeof StaffSignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/packages': typeof AuthenticatedPackagesRoute
  '/_authenticated/rates': typeof AuthenticatedRatesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/shipments': typeof AuthenticatedShipmentsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/track/$code': typeof TrackCodeRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/crm/contacts': typeof AuthenticatedCrmContactsRoute
  '/_authenticated/sourcing/pos': typeof AuthenticatedSourcingPosRoute
  '/_authenticated/treasury/accounts': typeof AuthenticatedTreasuryAccountsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pending-activation'
    | '/portal'
    | '/staff-signup'
    | '/dashboard'
    | '/deliveries'
    | '/invoices'
    | '/packages'
    | '/rates'
    | '/reports'
    | '/shipments'
    | '/support'
    | '/track/$code'
    | '/admin/users'
    | '/crm/contacts'
    | '/sourcing/pos'
    | '/treasury/accounts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pending-activation'
    | '/portal'
    | '/staff-signup'
    | '/dashboard'
    | '/deliveries'
    | '/invoices'
    | '/packages'
    | '/rates'
    | '/reports'
    | '/shipments'
    | '/support'
    | '/track/$code'
    | '/admin/users'
    | '/crm/contacts'
    | '/sourcing/pos'
    | '/treasury/accounts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pending-activation'
    | '/portal'
    | '/staff-signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/deliveries'
    | '/_authenticated/invoices'
    | '/_authenticated/packages'
    | '/_authenticated/rates'
    | '/_authenticated/reports'
    | '/_authenticated/shipments'
    | '/_authenticated/support'
    | '/track/$code'
    | '/_authenticated/admin/users'
    | '/_authenticated/crm/contacts'
    | '/_authenticated/sourcing/pos'
    | '/_authenticated/treasury/accounts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PendingActivationRoute: typeof PendingActivationRoute
  PortalRoute: typeof PortalRoute
  StaffSignupRoute: typeof StaffSignupRoute
  TrackCodeRoute: typeof TrackCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff-signup': {
      id: '/staff-signup'
      path: '/staff-signup'
      fullPath: '/staff-signup'
      preLoaderRoute: typeof StaffSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-activation': {
      id: '/pending-activation'
      path: '/pending-activation'
      fullPath: '/pending-activation'
      preLoaderRoute: typeof PendingActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$code': {
      id: '/track/$code'
      path: '/track/$code'
      fullPath: '/track/$code'
      preLoaderRoute: typeof TrackCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shipments': {
      id: '/_authenticated/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof AuthenticatedShipmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rates': {
      id: '/_authenticated/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof AuthenticatedRatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/packages': {
      id: '/_authenticated/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthenticatedPackagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treasury/accounts': {
      id: '/_authenticated/treasury/accounts'
      path: '/treasury/accounts'
      fullPath: '/treasury/accounts'
      preLoaderRoute: typeof AuthenticatedTreasuryAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sourcing/pos': {
      id: '/_authenticated/sourcing/pos'
      path: '/sourcing/pos'
      fullPath: '/sourcing/pos'
      preLoaderRoute: typeof AuthenticatedSourcingPosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/contacts': {
      id: '/_authenticated/crm/contacts'
      path: '/crm/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof AuthenticatedCrmContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeliveriesRoute: typeof AuthenticatedDeliveriesRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedPackagesRoute: typeof AuthenticatedPackagesRoute
  AuthenticatedRatesRoute: typeof AuthenticatedRatesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedShipmentsRoute: typeof AuthenticatedShipmentsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedCrmContactsRoute: typeof AuthenticatedCrmContactsRoute
  AuthenticatedSourcingPosRoute: typeof AuthenticatedSourcingPosRoute
  AuthenticatedTreasuryAccountsRoute: typeof AuthenticatedTreasuryAccountsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedPackagesRoute: AuthenticatedPackagesRoute,
  AuthenticatedRatesRoute: AuthenticatedRatesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedShipmentsRoute: AuthenticatedShipmentsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedCrmContactsRoute: AuthenticatedCrmContactsRoute,
  AuthenticatedSourcingPosRoute: AuthenticatedSourcingPosRoute,
  AuthenticatedTreasuryAccountsRoute: AuthenticatedTreasuryAccountsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PendingActivationRoute: PendingActivationRoute,
  PortalRoute: PortalRoute,
  StaffSignupRoute: StaffSignupRoute,
  TrackCodeRoute: TrackCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
